version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookabite
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
